# pandas を利用したデータ操作

- Python の pandas というライブラリを利用すると，dataframe という形式の表データを取り扱うことができる
- pandas を利用するには，まず `import pandas as pd` を実行する

※ 各コードの意味は理解しなくてもよい．実行の前後のデータから，何をしているのかをよく見ておくこと

In [1]:
# pandas ライブラリをインポートする (使える状態にする)
import pandas as pd

# 完了確認のメッセージ
print("完了!")

完了!

## dataframe の操作

- `pd.read_excel` という関数を用いると，**Excel ファイルの読み込み**ができる
- ほかには，CSV ファイルを読み込む `pd.read_csv` という関数もある

In [2]:
# data08.xlsx という Excel ファイルの「科目」というワークシートを読み込み，
# dataframe という形式で変数 subjects に代入する
subjects = pd.read_excel("data08.xlsx", sheet_name="科目")

# 変数 subjects の内容の表示
display(subjects)
# 変数の内容は，上のツールバーの「変数」からも確認できる

    科目番号         科目名  区分     先修
0  Sc184      IT基礎演習  IT      -
1  Sc185      IT応用演習  IT  Sc184
2  Sc188  データサイエンス入門  IT  Sc184
3  Sc285   プログラミング演習   P  Sc184
4  Sc287   マルチメディア演習   B  Sc185
5  Sc289      認知情報処理   P  Sc285

In [3]:
# data08.xlsx の「クラス」を classes に読み込み，内容を表示する
classes = pd.read_excel("data08.xlsx", sheet_name="クラス")
display(classes)

     科目番号  期 クラス 曜/時       教室   教員ID
0   Sc184  前   A  月1  JD201-2  f0001
1   Sc184  前   B  月2  JD201-2  f0001
2   Sc184  前   C  火1  JD201-2  p0003
3   Sc184  前   D  火2  JD201-2  p0003
4   Sc184  前   E  水1  JD201-2  f0002
5   Sc184  前   F  水2  JD201-2  f0002
6   Sc184  前   G  木1  JD201-2  p0002
7   Sc184  前   H  木2  JD201-2  p0001
8   Sc184  前   I  木3  JD201-2  p0001
9   Sc184  後   -  火3    JD202  p0003
10  Sc185  後   A  月2    JD202  f0001
11  Sc185  後   B  火1    JD202  p0003
12  Sc185  後   C  火2    JD202  p0003
13  Sc185  後   D  木1    JD202  p0002
14  Sc188  後   A  月1  JD201-2  f0001
15  Sc188  後   B  水1  JD201-2  f0002
16  Sc188  後   C  水2  JD201-2  f0002
17  Sc285  前   -  水3    JD202  f0002
18  Sc287  後   -  月4    JD202  f0001
19  Sc289  後   -  水3    JD202  f0002

In [4]:
# data08.xlsx の「専任教員」を fulltime に読み込み，内容を表示する
fulltime = pd.read_excel("data08.xlsx", sheet_name="専任教員")
display(fulltime)

    教員ID    教員名 勤務    研究室                  mail
0  f0001   出口 弘  専  JD313  dxxx@kc.kobe-c.ac.jp
1  f0002  三浦 欽也  専  JD315  mxxx@kc.kobe-c.ac.jp

In [5]:
# data08.xlsx の「非常勤教員」を parttime に読み込み，内容を表示する
parttime = pd.read_excel("data08.xlsx", sheet_name="非常勤教員")
display(parttime)

    教員ID    教員名 勤務 研究室                  mail
0  p0001  河井 泰子  非   -  kxxx@kc.kobe-c.ac.jp
1  p0002  鍋島 康之  非   -  nxxx@kc.kobe-c.ac.jp
2  p0003  高田 茂樹  非   -  txxx@kc.kobe-c.ac.jp

- まず，fulltime と parttime を1つの表 teachers にまとめる（**和**; **union**）
- 2つの表 (dataframe) の和は，`pd.concat` 関数で行える

※ 厳密には，さらに**重複した行を1行にまとめる**必要がある（その場合は，`.drop_duplicates()` を付ける）

In [6]:
# fulltime と parttime の和を teachers に代入し，内容を表示する
teachers = pd.concat([fulltime, parttime], ignore_index=True)   # .drop_duplicates()
display(teachers)

    教員ID    教員名 勤務    研究室                  mail
0  f0001   出口 弘  専  JD313  dxxx@kc.kobe-c.ac.jp
1  f0002  三浦 欽也  専  JD315  mxxx@kc.kobe-c.ac.jp
2  p0001  河井 泰子  非      -  kxxx@kc.kobe-c.ac.jp
3  p0002  鍋島 康之  非      -  nxxx@kc.kobe-c.ac.jp
4  p0003  高田 茂樹  非      -  txxx@kc.kobe-c.ac.jp

- 3つの表 (subjects, classes, teachers; いずれも dataframe) を**結合 (join)** する
- 2つの表 (dataframe) の結合は，`pd.merge` 関数で行える

In [7]:
# まず，classes と subjects を結合し，
# 結果の表 (dataframe) を joined1 に代入し，内容を表示する
joined1 = pd.merge(classes, subjects, on="科目番号")
display(joined1)

     科目番号  期 クラス 曜/時       教室   教員ID         科目名  区分     先修
0   Sc184  前   A  月1  JD201-2  f0001      IT基礎演習  IT      -
1   Sc184  前   B  月2  JD201-2  f0001      IT基礎演習  IT      -
2   Sc184  前   C  火1  JD201-2  p0003      IT基礎演習  IT      -
3   Sc184  前   D  火2  JD201-2  p0003      IT基礎演習  IT      -
4   Sc184  前   E  水1  JD201-2  f0002      IT基礎演習  IT      -
5   Sc184  前   F  水2  JD201-2  f0002      IT基礎演習  IT      -
6   Sc184  前   G  木1  JD201-2  p0002      IT基礎演習  IT      -
7   Sc184  前   H  木2  JD201-2  p0001      IT基礎演習  IT      -
8   Sc184  前   I  木3  JD201-2  p0001      IT基礎演習  IT      -
9   Sc184  後   -  火3    JD202  p0003      IT基礎演習  IT      -
10  Sc185  後   A  月2    JD202  f0001      IT応用演習  IT  Sc184
11  Sc185  後   B  火1    JD202  p0003      IT応用演習  IT  Sc184
12  Sc185  後   C  火2    JD202  p0003      IT応用演習  IT  Sc184
13  Sc185  後   D  木1    JD202  p0002      IT応用演習  IT  Sc184
14  Sc188  後   A  月1  JD201-2  f0001  データサイエンス入門  IT  Sc184
15  Sc188  後   B  水1  JD201-2  f0002  データサイエンス入門  IT  Sc184
16  Sc188  後   C  水2  JD201-2  f0002  データサイエンス入門  IT  Sc184
17  Sc285  前   -  水3    JD202  f0002   プログラミング演習   P  Sc184
18  Sc287  後   -  月4    JD202  f0001   マルチメディア演習   B  Sc185
19  Sc289  後   -  水3    JD202  f0002      認知情報処理   P  Sc285

In [8]:
# 次に，先に結合した joined1 と teachers を結合し，
# 結果の表 (dataframe) を joined2 に代入し，内容を表示する
joined2 = pd.merge(joined1, teachers, on="教員ID")
display(joined2)

,科目番号,期,クラス,曜/時,教室,教員ID,科目名,区分,先修,教員名,勤務,研究室,mail
0,Sc184,前,A,月1,JD201-2,f0001,IT基礎演習,IT,-,出口 弘,専,JD313,dxxx@kc.kobe-c.ac.jp
1,Sc184,前,B,月2,JD201-2,f0001,IT基礎演習,IT,-,出口 弘,専,JD313,dxxx@kc.kobe-c.ac.jp
2,Sc184,前,C,火1,JD201-2,p0003,IT基礎演習,IT,-,高田 茂樹,非,-,txxx@kc.kobe-c.ac.jp
3,Sc184,前,D,火2,JD201-2,p0003,IT基礎演習,IT,-,高田 茂樹,非,-,txxx@kc.kobe-c.ac.jp
4,Sc184,前,E,水1,JD201-2,f0002,IT基礎演習,IT,-,三浦 欽也,専,JD315,mxxx@kc.kobe-c.ac.jp
5,Sc184,前,F,水2,JD201-2,f0002,IT基礎演習,IT,-,三浦 欽也,専,JD315,mxxx@kc.kobe-c.ac.jp
6,Sc184,前,G,木1,JD201-2,p0002,IT基礎演習,IT,-,鍋島 康之,非,-,nxxx@kc.kobe-c.ac.jp
7,Sc184,前,H,木2,JD201-2,p0001,IT基礎演習,IT,-,河井 泰子,非,-,kxxx@kc.kobe-c.ac.jp
8,Sc184,前,I,木3,JD201-2,p0001,IT基礎演習,IT,-,河井 泰子,非,-,kxxx@kc.kobe-c.ac.jp
9,Sc184,後,-,火3,JD202,p0003,IT基礎演習,IT,-,高田 茂樹,非,-,txxx@kc.kobe-c.ac.jp
10,Sc185,後,A,月2,JD202,f0001,IT応用演習,IT,Sc184,出口 弘,専,JD313,dxxx@kc.kobe-c.ac.jp
11,Sc185,後,B,火1,JD202,p0003,IT応用演習,IT,Sc184,高田 茂樹,非,-,txxx@kc.kobe-c.ac.jp
12,Sc185,後,C,火2,JD202,p0003,IT応用演習,IT,Sc184,高田 茂樹,非,-,txxx@kc.kobe-c.ac.jp
13,Sc185,後,D,木1,JD202,p0002,IT応用演習,IT,Sc184,鍋島 康之,非,-,nxxx@kc.kobe-c.ac.jp
14,Sc188,後,A,月1,JD201-2,f0001,データサイエンス入門,IT,Sc184,出口 弘,専,JD313,dxxx@kc.kobe-c.ac.jp
15,Sc188,後,B,水1,JD201-2,f0002,データサイエンス入門,IT,Sc184,三浦 欽也,専,JD315,mxxx@kc.kobe-c.ac.jp
16,Sc188,後,C,水2,JD201-2,f0002,データサイエンス入門,IT,Sc184,三浦 欽也,専,JD315,mxxx@kc.kobe-c.ac.jp
17,Sc285,前,-,水3,JD202,f0002,プログラミング演習,P,Sc184,三浦 欽也,専,JD315,mxxx@kc.kobe-c.ac.jp
18,Sc287,後,-,月4,JD202,f0001,マルチメディア演習,B,Sc185,出口 弘,専,JD313,dxxx@kc.kobe-c.ac.jp
19,Sc289,後,-,水3,JD202,f0002,認知情報処理,P,Sc285,三浦 欽也,専,JD315,mxxx@kc.kobe-c.ac.jp

- dataframe で**選択** (**selection**; 特定の行を選び出す操作) を行う方法はいくつかある
- ここでは，"期" が "後" である行だけを選ぶ

In [9]:
# joined2 から，"期" が "後" に等しいという条件を満たす行を選択し，
# 結果の表 (dataframe) を selected に代入し，内容を表示する
selected = joined2[joined2["期"]=="後"]
display(selected)

,科目番号,期,クラス,曜/時,教室,教員ID,科目名,区分,先修,教員名,勤務,研究室,mail
9,Sc184,後,-,火3,JD202,p0003,IT基礎演習,IT,-,高田 茂樹,非,-,txxx@kc.kobe-c.ac.jp
10,Sc185,後,A,月2,JD202,f0001,IT応用演習,IT,Sc184,出口 弘,専,JD313,dxxx@kc.kobe-c.ac.jp
11,Sc185,後,B,火1,JD202,p0003,IT応用演習,IT,Sc184,高田 茂樹,非,-,txxx@kc.kobe-c.ac.jp
12,Sc185,後,C,火2,JD202,p0003,IT応用演習,IT,Sc184,高田 茂樹,非,-,txxx@kc.kobe-c.ac.jp
13,Sc185,後,D,木1,JD202,p0002,IT応用演習,IT,Sc184,鍋島 康之,非,-,nxxx@kc.kobe-c.ac.jp
14,Sc188,後,A,月1,JD201-2,f0001,データサイエンス入門,IT,Sc184,出口 弘,専,JD313,dxxx@kc.kobe-c.ac.jp
15,Sc188,後,B,水1,JD201-2,f0002,データサイエンス入門,IT,Sc184,三浦 欽也,専,JD315,mxxx@kc.kobe-c.ac.jp
16,Sc188,後,C,水2,JD201-2,f0002,データサイエンス入門,IT,Sc184,三浦 欽也,専,JD315,mxxx@kc.kobe-c.ac.jp
18,Sc287,後,-,月4,JD202,f0001,マルチメディア演習,B,Sc185,出口 弘,専,JD313,dxxx@kc.kobe-c.ac.jp
19,Sc289,後,-,水3,JD202,f0002,認知情報処理,P,Sc285,三浦 欽也,専,JD315,mxxx@kc.kobe-c.ac.jp

- **射影** (**projection**; 特定の列を選び出す操作) を行う方法もいくつかある
- ここでは，"科目番号", "科目名", "クラス", "教員名", "曜/時", "教室"
  をこの順に並べる

※ 厳密な意味での射影では，さらに**重複した行を1行にまとめる**必要がある（その場合は，`.drop_duplicates()` を付ける）

In [10]:
# selected から，指定した列を指定した順に抜き出して，
# 結果の表 (dataframe) を projected に代入し，内容を表示する
projected = selected[["科目番号", "科目名", "クラス", "教員名", "曜/時", "教室"]]   # .drop_duplicates()
display(projected)

     科目番号         科目名 クラス    教員名 曜/時       教室
9   Sc184      IT基礎演習   -  高田 茂樹  火3    JD202
10  Sc185      IT応用演習   A   出口 弘  月2    JD202
11  Sc185      IT応用演習   B  高田 茂樹  火1    JD202
12  Sc185      IT応用演習   C  高田 茂樹  火2    JD202
13  Sc185      IT応用演習   D  鍋島 康之  木1    JD202
14  Sc188  データサイエンス入門   A   出口 弘  月1  JD201-2
15  Sc188  データサイエンス入門   B  三浦 欽也  水1  JD201-2
16  Sc188  データサイエンス入門   C  三浦 欽也  水2  JD201-2
18  Sc287   マルチメディア演習   -   出口 弘  月4    JD202
19  Sc289      認知情報処理   -  三浦 欽也  水3    JD202

- 行の**並べ替え**は，`.sort_values` というメソッド (データの直後に付けて，データの操作をする関数) で行える

In [11]:
# projected の各行を，"科目番号" の順に並べ替える
# "科目番号" の等しいものに関しては，"クラス" の順に並べ替える
sorted = projected.sort_values(["科目番号", "クラス"])
display(sorted)

     科目番号         科目名 クラス    教員名 曜/時       教室
9   Sc184      IT基礎演習   -  高田 茂樹  火3    JD202
10  Sc185      IT応用演習   A   出口 弘  月2    JD202
11  Sc185      IT応用演習   B  高田 茂樹  火1    JD202
12  Sc185      IT応用演習   C  高田 茂樹  火2    JD202
13  Sc185      IT応用演習   D  鍋島 康之  木1    JD202
14  Sc188  データサイエンス入門   A   出口 弘  月1  JD201-2
15  Sc188  データサイエンス入門   B  三浦 欽也  水1  JD201-2
16  Sc188  データサイエンス入門   C  三浦 欽也  水2  JD201-2
18  Sc287   マルチメディア演習   -   出口 弘  月4    JD202
19  Sc289      認知情報処理   -  三浦 欽也  水3    JD202

- `.reset_index` メソッドで**インデックス (通し番号) の振り直し**ができる

In [12]:
# sorted のインデックスを振り直して，
# 結果の表 (dataframe) を final に代入する
final = sorted.reset_index(drop=True)
display(final)

    科目番号         科目名 クラス    教員名 曜/時       教室
0  Sc184      IT基礎演習   -  高田 茂樹  火3    JD202
1  Sc185      IT応用演習   A   出口 弘  月2    JD202
2  Sc185      IT応用演習   B  高田 茂樹  火1    JD202
3  Sc185      IT応用演習   C  高田 茂樹  火2    JD202
4  Sc185      IT応用演習   D  鍋島 康之  木1    JD202
5  Sc188  データサイエンス入門   A   出口 弘  月1  JD201-2
6  Sc188  データサイエンス入門   B  三浦 欽也  水1  JD201-2
7  Sc188  データサイエンス入門   C  三浦 欽也  水2  JD201-2
8  Sc287   マルチメディア演習   -   出口 弘  月4    JD202
9  Sc289      認知情報処理   -  三浦 欽也  水3    JD202

- `.to_csv` メソッドで，**CSVファイルへの保存**ができる

In [13]:
# 出来上がった表 (final) を，CSVファイル (data08final.csv) に保存する
# encoding="utf_8_sig" は，文字化け対策のために必要
final.to_csv("data08final.csv", index=False, encoding="utf_8_sig")

# 完了確認のメッセージ
print("完了!")

完了!

In [14]:
# 確認のため，改めて data08final.csv 読み込んで (dataframe に変換して) 表示する
reloaded = pd.read_csv("data08final.csv")
display(reloaded)

    科目番号         科目名 クラス    教員名 曜/時       教室
0  Sc184      IT基礎演習   -  高田 茂樹  火3    JD202
1  Sc185      IT応用演習   A   出口 弘  月2    JD202
2  Sc185      IT応用演習   B  高田 茂樹  火1    JD202
3  Sc185      IT応用演習   C  高田 茂樹  火2    JD202
4  Sc185      IT応用演習   D  鍋島 康之  木1    JD202
5  Sc188  データサイエンス入門   A   出口 弘  月1  JD201-2
6  Sc188  データサイエンス入門   B  三浦 欽也  水1  JD201-2
7  Sc188  データサイエンス入門   C  三浦 欽也  水2  JD201-2
8  Sc287   マルチメディア演習   -   出口 弘  月4    JD202
9  Sc289      認知情報処理   -  三浦 欽也  水3    JD202

## データクレンジング
データに表記のゆらぎや欠損値がある場合，データ処理が正しく行えないことがあるため，あらかじめ対処しておくこと．

- 表記のゆらぎがある場合，表記を統一する
- 欠損値 (NaN) のあるデータについては
  - 欠損値を適切な値で埋める
    - 同じレコードの他の値から求まる場合は，その値で埋める
    - 同じ列のデータを用いて，代表値 (平均値，中央値，最頻値など) で埋める

    など
  - 欠損値を含むレコード (行) を削除する

  のいずれかを行う

※ 各コードの意味は理解しなくてもよい．実行の前後のデータから，何をしているのかをよく見ておくこと

In [15]:
import pandas as pd

# サンプルデータの読み込みと表示
# data08.xlsx の「クレンジング前」を uriage_data に読み込み，内容を表示する
# (header=2 は，最初の2行を読み飛ばすためのもの)
uriage_data = pd.read_excel("data08.xlsx", sheet_name="クレンジング前", header=2)
display(uriage_data)

          日付   曜日   商品名   価格  個数 顧客の性別  顧客の年齢
0 2021-04-01    木   ノート  100   1    男性   24.0
1 2021-04-02    金    鉛筆   80   5    女性   16.0
2 2021-04-03    土  マジック  200   1    男性   15.0
3 2021-04-04  NaN  マジック  200   2    女性    9.0
4 2021-04-05    月   ノート  100   2    女性    NaN
5 2021-04-06    火   ハサミ  400   1   NaN   14.0
6 2021-04-07    水   はさみ  400   2    女性   19.0

### 表記のゆらぎの統一

In [16]:
# 表記のゆらぎの統一 (商品名の "はさみ", "ハサミ" は "ハサミ" に統一)
uriage_data["商品名"] = uriage_data["商品名"].str.replace("はさみ", "ハサミ")
display(uriage_data)

          日付   曜日   商品名   価格  個数 顧客の性別  顧客の年齢
0 2021-04-01    木   ノート  100   1    男性   24.0
1 2021-04-02    金    鉛筆   80   5    女性   16.0
2 2021-04-03    土  マジック  200   1    男性   15.0
3 2021-04-04  NaN  マジック  200   2    女性    9.0
4 2021-04-05    月   ノート  100   2    女性    NaN
5 2021-04-06    火   ハサミ  400   1   NaN   14.0
6 2021-04-07    水   ハサミ  400   2    女性   19.0

### 欠損値の補充

In [17]:
# 曜日の欠損値を日付から埋める
wd = ('月','火','水','木','金','土','日')
nans = uriage_data["曜日"].isna()
for i, row in uriage_data.loc[nans,:].iterrows():
    uriage_data.loc[i, "曜日"] = wd[row["日付"].weekday()]
display(uriage_data)

          日付 曜日   商品名   価格  個数 顧客の性別  顧客の年齢
0 2021-04-01  木   ノート  100   1    男性   24.0
1 2021-04-02  金    鉛筆   80   5    女性   16.0
2 2021-04-03  土  マジック  200   1    男性   15.0
3 2021-04-04  日  マジック  200   2    女性    9.0
4 2021-04-05  月   ノート  100   2    女性    NaN
5 2021-04-06  火   ハサミ  400   1   NaN   14.0
6 2021-04-07  水   ハサミ  400   2    女性   19.0

In [18]:
# 顧客の性別の欠損値を最頻値で埋める
mode_of_gender = uriage_data["顧客の性別"].mode()[0]   # 顧客の性別の最頻値
uriage_data["顧客の性別"] = uriage_data["顧客の性別"].fillna(mode_of_gender)
display(uriage_data)

          日付 曜日   商品名   価格  個数 顧客の性別  顧客の年齢
0 2021-04-01  木   ノート  100   1    男性   24.0
1 2021-04-02  金    鉛筆   80   5    女性   16.0
2 2021-04-03  土  マジック  200   1    男性   15.0
3 2021-04-04  日  マジック  200   2    女性    9.0
4 2021-04-05  月   ノート  100   2    女性    NaN
5 2021-04-06  火   ハサミ  400   1    女性   14.0
6 2021-04-07  水   ハサミ  400   2    女性   19.0

In [19]:
# 顧客の年齢の欠損値を平均値（を四捨五入した値）で埋める
mean_of_age = round(uriage_data["顧客の年齢"].mean())   # 顧客の年齢の平均値
uriage_data["顧客の年齢"] = uriage_data["顧客の年齢"].fillna(mean_of_age)
display(uriage_data)

          日付 曜日   商品名   価格  個数 顧客の性別  顧客の年齢
0 2021-04-01  木   ノート  100   1    男性   24.0
1 2021-04-02  金    鉛筆   80   5    女性   16.0
2 2021-04-03  土  マジック  200   1    男性   15.0
3 2021-04-04  日  マジック  200   2    女性    9.0
4 2021-04-05  月   ノート  100   2    女性   16.0
5 2021-04-06  火   ハサミ  400   1    女性   14.0
6 2021-04-07  水   ハサミ  400   2    女性   19.0

### 保存

In [20]:
# 出来上がった表 (uriage_data) を，CSVファイル (uriage_data.csv) に保存する
# encoding="utf_8_sig" は，文字化け対策のために必要
uriage_data.to_csv("uriage_data.csv", index=False, encoding="utf_8_sig")

# 完了確認のメッセージ
print("完了!")

完了!