# 「データの収集と加工」の課題
- task08.xlsx とこのファイル (task08.ipynb) を Sc188 にダウンロードした後，data08.ipynb の内容を参考に，以下の作業をしてみよう．(`"????"` の部分を，それぞれ正しい表現に書き直す)

In [1]:
# pandas ライブラリをインポートする (使える状態にする)
import pandas as pd

# 完了確認のメッセージ
print("完了!")

完了!

In [2]:
# ファイル "task08.xlsx" のワークシート "販売" を変数 hanbai に読み込む
# （「dataframe の操作」の「Excel ファイルの読み込み」を参考に）
hanbai = pd.read_excel("task08.xlsx", sheet_name="販売")
hanbai

    レシート番号 商品コード  個数
0    10001  d003   1
1    10002  m001   1
2    10002  s001   1
3    10002  d003   1
4    10003  m003   1
5    10003  m002   2
6    10003  d002   1
7    10004  m004   1
8    10004  s002   1
9    10005  d001   1
10   10005  m003   1
11   10005  d001   1

In [3]:
# ファイル "task08.xlsx" のワークシート "レシート" を変数 receipt に読み込む
# （「dataframe の操作」の「Excel ファイルの読み込み」を参考に）
receipt = pd.read_excel("task08.xlsx", sheet_name="レシート")
receipt

   レシート番号                  日時   性別    年齢
0   10001 2022-11-01 07:21:00    男  25.0
1   10002 2022-11-01 08:25:00  NaN  18.0
2   10003 2022-11-01 11:50:00    男   NaN
3   10004 2022-11-01 08:47:00    女  44.0
4   10005 2022-11-01 13:05:00    男  62.0

In [4]:
# ファイル "task08.xlsx" のワークシート "商品" を変数 shohin に読み込む
# （「dataframe の操作」の「Excel ファイルの読み込み」を参考に）
shohin = pd.read_excel("task08.xlsx", sheet_name="商品")
shohin

  商品コード         商品名   単価
0  m001        卵サンド  300
1  m002    おにぎり（ツナ）  120
2  m003         鮭弁当  330
3  m004      たまごサンド  300
4  s001      ポテトサラダ  210
5  s002       野菜スープ  180
6  d001     お茶500ml  150
7  d002  ウーロン茶500ml  150
8  d003       コーヒーS  100

In [5]:
# shohin を見ると，m001 と m004 は重複しているので，hanbai の "商品コード" で "m004" を "m001" に置き換える
# （「データクレンジング」の「表記のゆらぎの統一」を参考に）
hanbai["商品コード"] = hanbai["商品コード"].str.replace("m004", "m001")
hanbai

    レシート番号 商品コード  個数
0    10001  d003   1
1    10002  m001   1
2    10002  s001   1
3    10002  d003   1
4    10003  m003   1
5    10003  m002   2
6    10003  d002   1
7    10004  m001   1
8    10004  s002   1
9    10005  d001   1
10   10005  m003   1
11   10005  d001   1

In [6]:
# (課題には影響しないが) shohin から "商品コード" が "m004" の行を削除するには以下のようにする
shohin = shohin[shohin["商品コード"]!="m004"]
shohin

  商品コード         商品名   単価
0  m001        卵サンド  300
1  m002    おにぎり（ツナ）  120
2  m003         鮭弁当  330
4  s001      ポテトサラダ  210
5  s002       野菜スープ  180
6  d001     お茶500ml  150
7  d002  ウーロン茶500ml  150
8  d003       コーヒーS  100

In [7]:
# receipt の "性別" の欠損値を最頻値で補う
# （「データクレンジング」の「欠損値の補充」を参考に）
mode_of_gender = receipt["性別"].mode()[0]    # 性別の最頻値
receipt["性別"] = receipt["性別"].fillna(mode_of_gender)
receipt

   レシート番号                  日時 性別    年齢
0   10001 2022-11-01 07:21:00  男  25.0
1   10002 2022-11-01 08:25:00  男  18.0
2   10003 2022-11-01 11:50:00  男   NaN
3   10004 2022-11-01 08:47:00  女  44.0
4   10005 2022-11-01 13:05:00  男  62.0

In [8]:
# receipt の "年齢" の欠損値を平均値(の四捨五入)で補う
# （「データクレンジング」の「欠損値の補充」を参考に）
mean_of_age = round(receipt["年齢"].mean())   # 顧客の年齢の平均値
receipt["年齢"] = receipt["年齢"].fillna(mean_of_age)
receipt

   レシート番号                  日時 性別    年齢
0   10001 2022-11-01 07:21:00  男  25.0
1   10002 2022-11-01 08:25:00  男  18.0
2   10003 2022-11-01 11:50:00  男  37.0
3   10004 2022-11-01 08:47:00  女  44.0
4   10005 2022-11-01 13:05:00  男  62.0

In [9]:
# "レシート番号" を介して hanbai に receipt を結合して joined1 に代入する
# （「dataframe の操作」の「結合 (join)」を参考に）
joined1 = pd.merge(hanbai, receipt, on="レシート番号")
joined1

    レシート番号 商品コード  個数                  日時 性別    年齢
0    10001  d003   1 2022-11-01 07:21:00  男  25.0
1    10002  m001   1 2022-11-01 08:25:00  男  18.0
2    10002  s001   1 2022-11-01 08:25:00  男  18.0
3    10002  d003   1 2022-11-01 08:25:00  男  18.0
4    10003  m003   1 2022-11-01 11:50:00  男  37.0
5    10003  m002   2 2022-11-01 11:50:00  男  37.0
6    10003  d002   1 2022-11-01 11:50:00  男  37.0
7    10004  m001   1 2022-11-01 08:47:00  女  44.0
8    10004  s002   1 2022-11-01 08:47:00  女  44.0
9    10005  d001   1 2022-11-01 13:05:00  男  62.0
10   10005  m003   1 2022-11-01 13:05:00  男  62.0
11   10005  d001   1 2022-11-01 13:05:00  男  62.0

In [10]:
# "商品コード" を介して joined1 に shohin を結合し，joined に代入する
# （「dataframe の操作」の「結合 (join)」を参考に）
joined = pd.merge(joined1, shohin, on="商品コード")
joined

    レシート番号 商品コード  個数                  日時 性別    年齢         商品名   単価
0    10001  d003   1 2022-11-01 07:21:00  男  25.0       コーヒーS  100
1    10002  m001   1 2022-11-01 08:25:00  男  18.0        卵サンド  300
2    10002  s001   1 2022-11-01 08:25:00  男  18.0      ポテトサラダ  210
3    10002  d003   1 2022-11-01 08:25:00  男  18.0       コーヒーS  100
4    10003  m003   1 2022-11-01 11:50:00  男  37.0         鮭弁当  330
5    10003  m002   2 2022-11-01 11:50:00  男  37.0    おにぎり（ツナ）  120
6    10003  d002   1 2022-11-01 11:50:00  男  37.0  ウーロン茶500ml  150
7    10004  m001   1 2022-11-01 08:47:00  女  44.0        卵サンド  300
8    10004  s002   1 2022-11-01 08:47:00  女  44.0       野菜スープ  180
9    10005  d001   1 2022-11-01 13:05:00  男  62.0     お茶500ml  150
10   10005  m003   1 2022-11-01 13:05:00  男  62.0         鮭弁当  330
11   10005  d001   1 2022-11-01 13:05:00  男  62.0     お茶500ml  150

In [11]:
# joined の各行を，"日時" の順に並べ替えて sorted に代入する
# （「dataframe の操作」の「行の並べ替え」を参考に）
sorted = joined.sort_values("日時")
sorted

    レシート番号 商品コード  個数                  日時 性別    年齢         商品名   単価
0    10001  d003   1 2022-11-01 07:21:00  男  25.0       コーヒーS  100
1    10002  m001   1 2022-11-01 08:25:00  男  18.0        卵サンド  300
2    10002  s001   1 2022-11-01 08:25:00  男  18.0      ポテトサラダ  210
3    10002  d003   1 2022-11-01 08:25:00  男  18.0       コーヒーS  100
7    10004  m001   1 2022-11-01 08:47:00  女  44.0        卵サンド  300
8    10004  s002   1 2022-11-01 08:47:00  女  44.0       野菜スープ  180
4    10003  m003   1 2022-11-01 11:50:00  男  37.0         鮭弁当  330
5    10003  m002   2 2022-11-01 11:50:00  男  37.0    おにぎり（ツナ）  120
6    10003  d002   1 2022-11-01 11:50:00  男  37.0  ウーロン茶500ml  150
9    10005  d001   1 2022-11-01 13:05:00  男  62.0     お茶500ml  150
10   10005  m003   1 2022-11-01 13:05:00  男  62.0         鮭弁当  330
11   10005  d001   1 2022-11-01 13:05:00  男  62.0     お茶500ml  150

In [12]:
# sorted のインデックスを振り直して final に代入する
# （「dataframe の操作」の「インデックス (通し番号) の振り直し」を参考に）
final = sorted.reset_index(drop=True)
final

    レシート番号 商品コード  個数                  日時 性別    年齢         商品名   単価
0    10001  d003   1 2022-11-01 07:21:00  男  25.0       コーヒーS  100
1    10002  m001   1 2022-11-01 08:25:00  男  18.0        卵サンド  300
2    10002  s001   1 2022-11-01 08:25:00  男  18.0      ポテトサラダ  210
3    10002  d003   1 2022-11-01 08:25:00  男  18.0       コーヒーS  100
4    10004  m001   1 2022-11-01 08:47:00  女  44.0        卵サンド  300
5    10004  s002   1 2022-11-01 08:47:00  女  44.0       野菜スープ  180
6    10003  m003   1 2022-11-01 11:50:00  男  37.0         鮭弁当  330
7    10003  m002   2 2022-11-01 11:50:00  男  37.0    おにぎり（ツナ）  120
8    10003  d002   1 2022-11-01 11:50:00  男  37.0  ウーロン茶500ml  150
9    10005  d001   1 2022-11-01 13:05:00  男  62.0     お茶500ml  150
10   10005  m003   1 2022-11-01 13:05:00  男  62.0         鮭弁当  330
11   10005  d001   1 2022-11-01 13:05:00  男  62.0     お茶500ml  150

In [13]:
# 出来上がった表 (final) を，CSVファイル "task08final.csv" に保存する
# （「dataframe の操作」の「CSVファイルへの保存」を参考に）
final.to_csv("task08final.csv", index=False, encoding="utf_8_sig")

# 確認のため，改めて data08final.csv 読み込んで (dataframe に変換して) 表示する
pd.read_csv("task08final.csv")

    レシート番号 商品コード  個数                   日時 性別    年齢         商品名   単価
0    10001  d003   1  2022-11-01 07:21:00  男  25.0       コーヒーS  100
1    10002  m001   1  2022-11-01 08:25:00  男  18.0        卵サンド  300
2    10002  s001   1  2022-11-01 08:25:00  男  18.0      ポテトサラダ  210
3    10002  d003   1  2022-11-01 08:25:00  男  18.0       コーヒーS  100
4    10004  m001   1  2022-11-01 08:47:00  女  44.0        卵サンド  300
5    10004  s002   1  2022-11-01 08:47:00  女  44.0       野菜スープ  180
6    10003  m003   1  2022-11-01 11:50:00  男  37.0         鮭弁当  330
7    10003  m002   2  2022-11-01 11:50:00  男  37.0    おにぎり（ツナ）  120
8    10003  d002   1  2022-11-01 11:50:00  男  37.0  ウーロン茶500ml  150
9    10005  d001   1  2022-11-01 13:05:00  男  62.0     お茶500ml  150
10   10005  m003   1  2022-11-01 13:05:00  男  62.0         鮭弁当  330
11   10005  d001   1  2022-11-01 13:05:00  男  62.0     お茶500ml  150

- 実行後の このファイル **task08.ipynb** と **task08final.csv** の2つのファイルを課題として提出すること．