# [AI-interのPython3入門 ](https://ai-inter1.com/)
## [18. Pandasでデータ分析](https://ai-inter1.com/category/python-basic/python-pandas/)
### [Pandas DataFrameを徹底解説！(作成、行・列の追加と削除、indexなど)](https://ai-inter1.com/pandas-dataframe_basic/)

In [99]:
import pandas as pd
list1=[11,12,13]
display(pd.DataFrame(data=list1))
display(pd.DataFrame(list1))
display(pd.DataFrame([[1,2,3]]))

    0
0  11
1  12
2  13

    0
0  11
1  12
2  13

   0  1  2
0  1  2  3

In [17]:
import pandas as pd
dict1 = {"Col1":[1,21,31], "Col2":[2,22,32], "Col3":[3,23,33]}
# dict1 = dict(Col1=[1,21,31], Col2=[2,22,32], Col3=[3,23,33]) # でも同じ
display(pd.DataFrame(dict1))

   Col1  Col2  Col3
0     1     2     3
1    21    22    23
2    31    32    33

In [18]:
import pandas as pd
df=pd.DataFrame()
df["Col1"]=[1,21,31]
df["Col2"]=[2,22,32]
df["Col3"]=[3,23,33]
display(df)

   Col1  Col2  Col3
0     1     2     3
1    21    22    23
2    31    32    33

In [29]:
import pandas as pd
list1=[11,12,13]
display(pd.DataFrame(list1))
display(pd.DataFrame(list1, columns=["Col1"]))
display(pd.DataFrame(list1, columns=["Col1"], index=[1001,1002,1003]))

    0
0  11
1  12
2  13

   Col1
0    11
1    12
2    13

      Col1
1001    11
1002    12
1003    13

### [Pandas Excel、CSVファイルの読み込み、書き込み(出力)](https://ai-inter1.com/python-pandas_csv/)

In [ ]:
import pandas as pd
url = "https://raw.githubusercontent.com/AileenNielsen/TimeSeriesAnalysisWithPython/master/data/AirPassengers.csv"

df = pd.read_csv(url)
display(df)
print(df.info())
print(df.index)

df.to_csv("AP.csv")
df.to_csv("AP_noindex.csv", index=None)

with pd.ExcelWriter('AP.xlsx') as writer:
    df.to_excel(writer, sheet_name="AP")
    df.to_excel(writer, sheet_name="AP_noindex", index=None, )

df2 = pd.read_csv(url, index_col='Month')
display(df2)
print(df2.info())
print(df2.index)

df2.to_csv("AP2.csv")
with pd.ExcelWriter('AP.xlsx',engine='openpyxl', mode='a') as writer2:
    df2.to_excel(writer2, sheet_name="AP2")

In [64]:
#### つづき
display(pd.read_csv("AP.csv"))
display(pd.read_csv("AP.csv", index_col=0))
display(pd.read_csv("AP_noindex.csv"))

display(pd.read_excel("AP.xlsx", sheet_name="AP"))
display(pd.read_excel("AP.xlsx", sheet_name="AP", index_col=0))
display(pd.read_excel("AP.xlsx", sheet_name="AP_noindex"))

     Unnamed: 0    Month  #Passengers
0             0  1949-01          112
1             1  1949-02          118
2             2  1949-03          132
3             3  1949-04          129
4             4  1949-05          121
..          ...      ...          ...
139         139  1960-08          606
140         140  1960-09          508
141         141  1960-10          461
142         142  1960-11          390
143         143  1960-12          432

[144 rows x 3 columns]

       Month  #Passengers
0    1949-01          112
1    1949-02          118
2    1949-03          132
3    1949-04          129
4    1949-05          121
..       ...          ...
139  1960-08          606
140  1960-09          508
141  1960-10          461
142  1960-11          390
143  1960-12          432

[144 rows x 2 columns]

       Month  #Passengers
0    1949-01          112
1    1949-02          118
2    1949-03          132
3    1949-04          129
4    1949-05          121
..       ...          ...
139  1960-08          606
140  1960-09          508
141  1960-10          461
142  1960-11          390
143  1960-12          432

[144 rows x 2 columns]

     Unnamed: 0    Month  #Passengers
0             0  1949-01          112
1             1  1949-02          118
2             2  1949-03          132
3             3  1949-04          129
4             4  1949-05          121
..          ...      ...          ...
139         139  1960-08          606
140         140  1960-09          508
141         141  1960-10          461
142         142  1960-11          390
143         143  1960-12          432

[144 rows x 3 columns]

       Month  #Passengers
0    1949-01          112
1    1949-02          118
2    1949-03          132
3    1949-04          129
4    1949-05          121
..       ...          ...
139  1960-08          606
140  1960-09          508
141  1960-10          461
142  1960-11          390
143  1960-12          432

[144 rows x 2 columns]

       Month  #Passengers
0    1949-01          112
1    1949-02          118
2    1949-03          132
3    1949-04          129
4    1949-05          121
..       ...          ...
139  1960-08          606
140  1960-09          508
141  1960-10          461
142  1960-11          390
143  1960-12          432

[144 rows x 2 columns]

- DataFrameへの行・列の追加と削除

In [116]:
import pandas as pd
dict1 = {"Col1":[1,2,3], "Col2":[11,12,13], "Col3":[21,22,23]}
df4 = pd.DataFrame(dict1, index=[0,2,1])
display(df4)

print("===行の追加===")
# 1行の DateFrame を作って，列名を合わせて pd.concat() を使う
display(pd.concat([df4, pd.DataFrame([[4,14,24]], columns=df4.columns)]))
# index を振り直すなら，ignore_index=True を付ける
display(pd.concat([df4, pd.DataFrame([[4,14,24]], columns=df4.columns)], ignore_index=True))
# index の重複を避けるなら，こんな手もある
display(pd.concat([df4, pd.DataFrame([[4,14,24]], columns=df4.columns, index=[max(df4.index)+1])]))

# df を書き換えてもよければ，.loc() が使える
df4.loc[max(df4.index)+1] = [4,14,24]
display(df4)

print("===列の追加===")
# df["Col4"]=...
# df.assign(...)
# df.insert(...)
# pd.concat(..., axis=1) - pass?

   Col1  Col2  Col3
0     1    11    21
2     2    12    22
1     3    13    23

===行の追加===

   Col1  Col2  Col3
0     1    11    21
2     2    12    22
1     3    13    23
0     4    14    24

   Col1  Col2  Col3
0     1    11    21
1     2    12    22
2     3    13    23
3     4    14    24

   Col1  Col2  Col3
0     1    11    21
2     2    12    22
1     3    13    23
3     4    14    24

   Col1  Col2  Col3
0     1    11    21
2     2    12    22
1     3    13    23
3     4    14    24

===列の追加===

- 行，列の書き換え