In [22]:
import pandas as pd
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=["A","B","C"], index=[1001,1002,1003])
df

      A  B  C
1001  1  2  3
1002  4  5  6
1003  7  8  9

In [23]:
display(df["B"])
display(df[["B"]])
display(df[["A","C"]])
display(df[["C","A"]])

1001    2
1002    5
1003    8
Name: B, dtype: int64

      B
1001  2
1002  5
1003  8

      A  C
1001  1  3
1002  4  6
1003  7  9

      C  A
1001  3  1
1002  6  4
1003  9  7

In [25]:
display(df.loc[1001])
display(df.iloc[1])

A    1
B    2
C    3
Name: 1001, dtype: int64

A    4
B    5
C    6
Name: 1002, dtype: int64

AttributeError: 'DataFrame' object has no attribute 'reverse'