In [64]:
import pandas as pd
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=["A","B","C"], index=[1001,1002,1003])
df

      A  B  C
1001  1  2  3
1002  4  5  6
1003  7  8  9

In [ ]:
display(df["B"])                # Series
display(df["B"][1003])          # スカラー
display(df["B"][[1001, 1003]])  # Series
display(df["B"][1:3])           # Series

1001    2
1002    5
1003    8
Name: B, dtype: int64

np.int64(8)

1001    2
1003    8
Name: B, dtype: int64

1002    5
1003    8
Name: B, dtype: int64

In [80]:
display(df[1:3])            # DataFrame

      A  B  C
1002  4  5  6
1003  7  8  9

In [ ]:
display(df[[True, False, True]])    # DataFrame
display(df.index % 2 == 1)          # array
display(df[df.index % 2 == 1])      # DataFrame

      A  B  C
1001  1  2  3
1003  7  8  9

array([ True, False,  True])

      A  B  C
1001  1  2  3
1003  7  8  9

In [90]:
display(df[["B"]])                              # DataFrame
display(df[["A", "C"]])                         # DataFrame
display(df[["C", "A"]])                         # DataFrame
display(df[["C", "A"]][1:3])                    # DataFrame
display(df[["C", "A"]][[True, False, True]])    # DataFrame

      B
1001  2
1002  5
1003  8

      A  C
1001  1  3
1002  4  6
1003  7  9

      C  A
1001  3  1
1002  6  4
1003  9  7

      C  A
1002  6  4
1003  9  7

      C  A
1001  3  1
1003  9  7

In [69]:
display(df.loc[1001])
display(df.iloc[1])

A    1
B    2
C    3
Name: 1001, dtype: int64

A    4
B    5
C    6
Name: 1002, dtype: int64